ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000
spring:
  cloud:
    sentinel:
      datasource:
        ds1:
          nacos:
            server-addr: ${mall.nacos.server-addr}
            data-id: sentinel-flow
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow
        ds2:
          nacos:
            server-addr: ${mall.nacos.server-addr}
            dataId: sentinel-degrade
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: degrade